### PR TITLE
Add get user margin

### PR DESCRIPTION
**Pull request by eduardoscottini**
Ref.: https://www.bitmex.com/api/explorer/#!/User/User_getMargin

### CODE REVIEW

**Comment by rupurt** [comment]
Hey @eduardoscottini,

Thanks for the PR. It looks really good. But what's the reason behind the change to config and the module variables?

**Comment by eduardoscottini** [comment]
Hi @rupurt,

In this format the config can be changed at runtime.

https://elixir-lang.org/getting-started/module-attributes.html
https://ropig.com/blog/be-careful-when-using-elixirs-module-attributes/

**Comment by rupurt** [comment]
Hi @eduardoscottini,

Those values are intended to be compile time values. Can you expand on why you need to change them at run time?

**Comment by eduardoscottini** [comment]
I intend to use this lib in a project with [release task](https://hexdocs.pm/mix/Mix.Tasks.Release.html#module-customization-and-configuration-summary) and it use a file `config/releases.exs` executed in runtime. The build executed by CI don't have this config file during the proccess.

**Comment by rupurt** [comment]
Can you add the configuration to `config/releases.exs`?

**Comment by eduardoscottini** [comment]
Yes, something like this:
```
#config/releases.exs

config :project_exemple, ProjectExample.ExBitmex,
  domain: System.get_env("BITMEX_DOMAIN", "www.bitmex.com")
```

and the docker-compose file contains all environment variables.

I needed this, because I have multiple production environments for homologation and QA.

**Comment by rupurt** [comment]
Gotcha. That sounds like a cool setup. I should do that :)

Can you pull those changes out and submit them in a separate PR?

**Comment by eduardoscottini** [comment]
Done! :)

https://github.com/fremantle-capital/ex_bitmex/pull/11

**Comment by rupurt** [comment]
Thanks @eduardoscottini. Can rebase this with master?

**Comment by eduardoscottini** [comment]
Done

**Comment by rupurt** [comment]
Can you remove the other commits so we can keep a clean history. It seems like you should only need 0685e3847e09dd2c00ee50bf4a117c8637cae6b2 now

**Comment by eduardoscottini** [comment]
Done

**Comment by rupurt** [comment]
Sweet, thanks @eduardoscottini 🍻 

I've got another project that uses this BitMEX wrapper that you might be interested in https://github.com/fremantle-capital/tai

**Comment by eduardoscottini** [comment]
Nice project!

You can publish a new version with this changes?

**Comment by rupurt** [comment]
@eduardoscottini done. Released as `v0.3.0`

**Pull request merged**
